### ISSUE TITLE
Make logging optional

### ISSUE THREAD

**Issue by ammgws** [ammgws/wynbot#1]

**Comment by WnndGws** [comment]
Is your wish to have a click flag? 
eg. --log-level <debug|info|error>

**Comment by ammgws** [comment]
Just an option to disable logging completely.

**Comment by WnndGws** [comment]
Disable logging completely?

**Comment by ammgws** [comment]
https://github.com/ammgws/gmailer_oauth/commit/fa6fcdc8b82792433cce116af1cb745480f8e854#diff-35b3150dbc555c54f87ca28b910ae855

**Comment by ammgws** [comment]
Implemented in 8193f18eb15acb56df5e19f9295347206a62f551

Thank you @WnndGws 
![image](https://user-images.githubusercontent.com/20397027/137575622-3a65fefd-d4ed-495c-95f4-ef3704a9cdc8.png)
